In [1]:
import pandas as pd
import numpy as np

In [5]:
oil = pd.read_csv('oil.csv')
oil.head()

oil.columns = ['Date','Price']

In [7]:
oil.shape

(1218, 2)

In [8]:
oil.index

RangeIndex(start=0, stop=1218, step=1)

In [12]:
oil.columns
oil.columns = ['day','price']
oil.head()

          day  price
0  2013-01-01    NaN
1  2013-01-02  93.14
2  2013-01-03  92.97
3  2013-01-04  93.12
4  2013-01-07  93.20

In [13]:
oil.axes

[RangeIndex(start=0, stop=1218, step=1),
 Index(['day', 'price'], dtype='object')]

In [16]:
oil.dtypes

day       object
price    float64
dtype: object

### Info & Describe

In [20]:
oil.head()
oil.tail()
oil.sample()

            day  price
700  2015-09-08  45.92

In [21]:
oil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   day     1218 non-null   object
 1   price   1175 non-null   float64
dtypes: float64(1), object(1)
memory usage: 19.2+ KB

In [23]:
oil.describe()
oil.describe(include='all')

               day        price
count         1218  1175.000000
unique        1218          NaN
top     2017-08-31          NaN
freq             1          NaN
mean           NaN    67.714366
std            NaN    25.630476
min            NaN    26.190000
25%            NaN    46.405000
50%            NaN    53.190000
75%            NaN    95.660000
max            NaN   110.620000

### Accessing Data Frame

In [26]:
oil.columns = ['Data','Oil Price']
oil.head()

         Data  Oil Price
0  2013-01-01        NaN
1  2013-01-02      93.14
2  2013-01-03      92.97
3  2013-01-04      93.12
4  2013-01-07      93.20

In [27]:
oil.Data
oil['Data']
oil['Oil Price']

0         NaN
1       93.14
2       92.97
3       93.12
4       93.20
        ...
1213    47.65
1214    46.40
1215    46.46
1216    45.96
1217    47.26
Name: Oil Price, Length: 1218, dtype: float64

### loc & iloc

In [29]:
oil['Euro Price'] = oil['Oil Price'] * 1.1
oil.head()

         Data  Oil Price  Euro Price
0  2013-01-01        NaN         NaN
1  2013-01-02      93.14     102.454
2  2013-01-03      92.97     102.267
3  2013-01-04      93.12     102.432
4  2013-01-07      93.20     102.520

In [31]:
oil.iloc[:10]
oil.iloc[:10, :]

         Data  Oil Price  Euro Price
0  2013-01-01        NaN         NaN
1  2013-01-02      93.14     102.454
2  2013-01-03      92.97     102.267
3  2013-01-04      93.12     102.432
4  2013-01-07      93.20     102.520
5  2013-01-08      93.21     102.531
6  2013-01-09      93.08     102.388
7  2013-01-10      93.81     103.191
8  2013-01-11      93.60     102.960
9  2013-01-14      94.27     103.697

In [35]:
oil.iloc[:10, -1]

0        NaN
1    102.454
2    102.267
3    102.432
4    102.520
5    102.531
6    102.388
7    103.191
8    102.960
9    103.697
Name: Euro Price, dtype: float64

In [41]:
oil.loc[:5, 'Data']
oil.loc[:5, ['Data']]

         Data
0  2013-01-01
1  2013-01-02
2  2013-01-03
3  2013-01-04
4  2013-01-07
5  2013-01-08

In [42]:
oil.loc[:5, 'Data':'Euro Price']

         Data  Oil Price  Euro Price
0  2013-01-01        NaN         NaN
1  2013-01-02      93.14     102.454
2  2013-01-03      92.97     102.267
3  2013-01-04      93.12     102.432
4  2013-01-07      93.20     102.520
5  2013-01-08      93.21     102.531

### Dropping Columns

In [43]:
oil['Euro Price'] = oil['Oil Price'] * 1.1
oil.head()

         Data  Oil Price  Euro Price
0  2013-01-01        NaN         NaN
1  2013-01-02      93.14     102.454
2  2013-01-03      92.97     102.267
3  2013-01-04      93.12     102.432
4  2013-01-07      93.20     102.520

In [47]:
oil.drop('Oil Price', axis=1).head()

         Data  Euro Price
0  2013-01-01         NaN
1  2013-01-02     102.454
2  2013-01-03     102.267
3  2013-01-04     102.432
4  2013-01-07     102.520

In [48]:
oil.drop(1, axis=0).head()

         Data  Oil Price  Euro Price
0  2013-01-01        NaN         NaN
2  2013-01-03      92.97     102.267
3  2013-01-04      93.12     102.432
4  2013-01-07      93.20     102.520
5  2013-01-08      93.21     102.531

### Identifing Duplicate rows

In [6]:
oil['Euro Price'] = oil['Price'] * 1.1
oil.head()

         Date  Price  Euro Price
0  2013-01-01    NaN         NaN
1  2013-01-02  93.14     102.454
2  2013-01-03  92.97     102.267
3  2013-01-04  93.12     102.432
4  2013-01-07  93.20     102.520

In [17]:
linha = oil.iloc[-1]
oil = pd.concat([oil, linha], ignore_index=True)

oil.shape

(1229, 4)

In [15]:
oil.nunique(dropna=False)

Date          1219
Price          999
Euro Price     999
0                4
dtype: int64

In [18]:
oil.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1224     True
1225     True
1226     True
1227     True
1228     True
Length: 1229, dtype: bool

In [21]:
oil.drop_duplicates(keep='last', ignore_index=True)

            Date  Price  Euro Price           0
0     2013-01-01    NaN         NaN         NaN
1     2013-01-02  93.14     102.454         NaN
2     2013-01-03  92.97     102.267         NaN
3     2013-01-04  93.12     102.432         NaN
4     2013-01-07  93.20     102.520         NaN
...          ...    ...         ...         ...
1217  2017-08-31  47.26      51.986         NaN
1218         NaN    NaN         NaN  2017-08-31
1219         NaN    NaN         NaN       47.26
1220         NaN    NaN         NaN         NaN
1221         NaN    NaN         NaN      51.986

[1222 rows x 4 columns]

### Missing data

In [23]:
oil.isna()
oil.isna().sum()

Date            11
Price           54
Euro Price      54
0             1224
dtype: int64

In [26]:
oil.fillna(0).head()

         Date  Price  Euro Price  0
0  2013-01-01   0.00       0.000  0
1  2013-01-02  93.14     102.454  0
2  2013-01-03  92.97     102.267  0
3  2013-01-04  93.12     102.432  0
4  2013-01-07  93.20     102.520  0

### Filtering DataFrames

In [54]:
oil = pd.read_csv('oil.csv', parse_dates=['date'])

oil.columns = ['Date','Price']

oil['benchmark'] = 100

oil.head()

        Date  Price  benchmark
0 2013-01-01    NaN        100
1 2013-01-02  93.14        100
2 2013-01-03  92.97        100
3 2013-01-04  93.12        100
4 2013-01-07  93.20        100

In [28]:
oil.describe()

             Price  benchmark
count  1175.000000     1218.0
mean     67.714366      100.0
std      25.630476        0.0
min      26.190000      100.0
25%      46.405000      100.0
50%      53.190000      100.0
75%      95.660000      100.0
max     110.620000      100.0

In [36]:
oil.loc[oil['Price'] > 100].head()
oil.loc[oil['Price'] > oil['benchmark']].head()

           Date   Price  benchmark
131  2013-07-03  101.92        100
133  2013-07-05  103.09        100
134  2013-07-08  103.03        100
135  2013-07-09  103.46        100
136  2013-07-10  106.41        100

In [39]:
oil.loc[oil['Date'].str[:4] == '2013'].head()

         Date  Price  benchmark
0  2013-01-01    NaN        100
1  2013-01-02  93.14        100
2  2013-01-03  92.97        100
3  2013-01-04  93.12        100
4  2013-01-07  93.20        100

In [42]:
mask = ((oil['Date'].str[:4] == '2013') 
        & (oil['Price'] > oil['benchmark']))

In [43]:
oil.loc[mask].head()

           Date   Price  benchmark
131  2013-07-03  101.92        100
133  2013-07-05  103.09        100
134  2013-07-08  103.03        100
135  2013-07-09  103.46        100
136  2013-07-10  106.41        100

### Query

In [56]:
oil.query('Price > benchmark')
oil.query('Price > benchmark or Date.dt.year == 2013')

          Date   Price  benchmark
0   2013-01-01     NaN        100
1   2013-01-02   93.14        100
2   2013-01-03   92.97        100
3   2013-01-04   93.12        100
4   2013-01-07   93.20        100
..         ...     ...        ...
407 2014-07-24  102.76        100
408 2014-07-25  105.23        100
409 2014-07-28  105.68        100
410 2014-07-29  104.91        100
411 2014-07-30  104.29        100

[367 rows x 3 columns]

### Sorting

In [2]:
oil = pd.read_csv('oil.csv', parse_dates=['date'])

oil.columns = ['Date','Price']

oil['benchmark'] = 100

oil.head()

        Date  Price  benchmark
0 2013-01-01    NaN        100
1 2013-01-02  93.14        100
2 2013-01-03  92.97        100
3 2013-01-04  93.12        100
4 2013-01-07  93.20        100

In [5]:
oil.sort_index(ascending=False)
oil.sort_index(ascending=True, axis=1)

           Date  Price  benchmark
0    2013-01-01    NaN        100
1    2013-01-02  93.14        100
2    2013-01-03  92.97        100
3    2013-01-04  93.12        100
4    2013-01-07  93.20        100
...         ...    ...        ...
1213 2017-08-25  47.65        100
1214 2017-08-28  46.40        100
1215 2017-08-29  46.46        100
1216 2017-08-30  45.96        100
1217 2017-08-31  47.26        100

[1218 rows x 3 columns]

In [13]:
oil.sort_values('Price', ascending=False)
oil.sort_values(['Price', 'Date'], ascending=[False, True]).head()

          Date   Price  benchmark
178 2013-09-06  110.62        100
171 2013-08-28  110.17        100
179 2013-09-09  109.62        100
170 2013-08-27  109.11        100
182 2013-09-12  108.72        100

### Modifying Columns (Comeback later)